ckpt: ./chkpts/sd-v1-4.ckpt
clip_grad: 200.0
color_weight: 100
ddim_eta: 0.0
ddim_steps: 500
edit_mask_path: ''
flow_weight: 10
guidance_schedule_path: data/guidance_schedule.npy
guidance_weight: 300.0
input_dir: ./assets/gpua_ultra_apple_right
log_freq: 0
mixed_precision: true
no_init_startzt: false
no_occlusion_masking: false
num_recursive_steps: 5
num_samples: 1
oracle_flow: true
prompt: an apple on a wooden table
save_dir: results/gpua_ultra_apple_right
scale: 7.5
sd_model_config: configs/stable-diffusion/v1-inference.yaml
target_flow_name: null
use_cached_latents: false
