ckpt: ./chkpts/sd-v1-4.ckpt
clip_grad: 200.0
color_weight: 100.0
ddim_eta: 0.0
ddim_steps: 500
edit_mask_path: ''
flow_weight: 3.0
guidance_schedule_path: data/guidance_schedule.npy
guidance_weight: 300.0
input_dir: ./assets/topiary_up
log_freq: 0
mixed_precision: true
no_init_startzt: false
no_occlusion_masking: false
num_recursive_steps: 3
num_samples: 1
oracle_flow: false
prompt: photo of topiary
save_dir: results/topiary_up
scale: 7.5
sd_model_config: configs/stable-diffusion/v1-inference.yaml
target_flow_name: null
use_cached_latents: false
